name: Deploy to Hetzner Server

on:
  push:
    branches:
      - master  # Trigger deployment when changes are pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Node.js and dependencies
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version required by your project

      - name: Install Dependencies
        run: npm install

      # Step 3: Build the project
      - name: Build the Project
        run: npm run build

      # Step 4: Deploy to the Hetzner server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 178.156.130.162  # Replace with your server's IP
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf /var/www/iron-wing-dispatching/*
            scp -r dist/* root@178.156.130.162:/var/www/iron-wing-dispatching
