name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies and build the project
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

       # Step 3: Debug dist folder
      - name: Debug dist folder
        run: |
          echo "Contents of dist folder:"
          ls -la /home/runner/work/iron-wing-dispatching/iron-wing-dispatching/dist || echo "dist folder does not exist!"

      - name: Debug Workspace
        run: |
          echo "Current working directory:"
          pwd
          echo "Workspace contents:"
          ls -la

      # Step 4: Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 178.156.130.162 >> ~/.ssh/known_hosts

      # Step 5: Debug SSH connection
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 178.156.130.162
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "SSH connection successful!"
            hostname
            ls -la /root

      # Step 6: Deploy to the server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 178.156.130.162
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Copying files to server....."
            rm -rf /var/www/iron-wing-dispatching/dist
            mkdir -p /var/www/iron-wing-dispatching
            rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" /home/runner/work/iron-wing-dispatching/iron-wing-dispatching/dist/ root@178.156.130.162:/var/www/iron-wing-dispatching/dist/
